<?
# Include Header
include('header.php');
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Bindinator - Add DNS Zone</title>
<link href="../bindinator.css" rel="stylesheet" type="text/css" />
</head>

<body>
<table width="90%" border="0" align="center" id="mainTable">
  <tr>
    <td align="center" valign="middle" bgcolor="#000000"><div align="center"><img src="../images/bindinator_logo_long.jpg" alt="Bindinator" width="350" height="125" /></div></td>
  </tr>
  <tr>
    <td><div align="center">
      <p class="style3"><a name="top" id="top"></a><a href="../index.php">Home</a> &gt; <a href="index.php">Administration</a> &gt; Add Zone</p>
      <p class="style1">Bindinator Backend Administration</p>
<?
if(isset($_GET['name']) && isset($_GET['fqname'])) {
	if(validHostname($_GET['name']) || validIP($_GET['name'])) {
		if(isFQDN($_GET['fqname'])) {
			if(!ereg("\.$", $_GET['fqname'])) { $_GET['fqname'] .= "."; }
			if($_GET['rev'] == 0 || $_GET['rev'] == 1) {
				if($_GET['rev'] == 1) {
					$query = "INSERT INTO ZONES (name,ichange,echange,fqname,rev,class) VALUES
					('".$_GET['name']."',
					1,
					1,
					'".$_GET['fqname']."',
					".$_GET['rev'].",
					'".$_GET['class']."')";
				} else {
					$query = "INSERT INTO ZONES (name,ichange,echange,fqname,rev) VALUES
					('".$_GET['name']."',
					0,
					0,
					'".$_GET['fqname']."',
					".$_GET['rev'].")";
				}
				# ADD To DB
				if($addected = insertSet($db, $query)) {
					// Copy generic template and mod ? - Later version
					$msg = "Added DNS Zone ".$_GET['fqname']." with name ".$_GET['name']." by user ".$_SERVER['PHP_AUTH_USER'];
					echo "<p align=\"center\">$msg</p>\n";
					echo "<p align=\"center\">Please create a zone template for this new zone or gernerating Zone files will fail.</p>\n";
					writeToLog("--> $msg", false);
				} else {
					$err = "!--> ERROR: Error inserting zone to DB. Please check logs.";
					echo "<p align=\"center\">$err</p>\n";
					writeToLog($err, true);
			
				}
			} else {
				$err = "!--> ERROR: Invalid Rev value ...";
				echo "<p align=\"center\">$err</p>\n";
				writeToLog($err, true);
			}
		} else {
			$err = "!--> ERROR: Invalid zonename";
			echo "<p align=\"center\">$err</p>\n";
			writeToLog($err, true);
		}
	} else {
		$err = "!--> ERROR: Invalid zonename";
		echo "<p align=\"center\">$err</p>\n";
		writeToLog($err, true);
	}
} else {
?>
      <form name="addZone" id="addZone" action="<? echo $_SERVER['PHP_SELF']; ?>" method="get">
      <table width="90%" border="0">
        <tr>
          <td colspan="2" bgcolor="#CCCCCC"><div align="center"><span class="style1">Add DNS Zone<br />
          </span><span class="style3">This will add a new zone that can be used to be dyncamically generated by Bindinator. Please enter reverse zones short form name as a Valid IP address (e.g. the Network address)</span></div></td>          </tr>
        <tr>
          <td width="50%">Zone Name:<br />
            <span class="style3">- Short Form name</span></td>
          <td width="50%"><input name="name" type="text" id="name" size="25" maxlength="20" /></td>
        </tr>
        <tr>
          <td width="50%"><p>Zone FQDN:<br />
            <span class="style3">Fully Qualified Domain Name</span></p>
            </td>
          <td width="50%"><input name="fqname" type="text" id="fqname" size="40" maxlength="35" /></td>
        </tr>
        <tr>
          <td width="50%"><p>Reverse Zone:<br />
            <span class="style3">Yes or No</span></p>
            </td>
          <td width="50%"><select name="rev" id="rev">
            <option value="1">Yes</option>
            <option value="0" selected>No</option>
          </select></td>
        </tr>
        <tr>
          <td width="50%"><p>Reverse Network Class:<br />
            <span class="style3">Class B or C Supported</span></p>
            </td>
          <td width="50%"><select name="class" id="class">
            <option value="b">Class B</option>
            <option value="c" selected>Class C</option>
          </select></td>
        </tr>
        <tr>
          <td colspan="2"><div align="center">
            <input type="submit" name="submit" id="submit" value="Add Zone" />
            <input type="reset" name="Reset" id="button" value="Reset" />
          </div>
          <div align="center"></div></td>
          </tr>
      </table>
      </form>
<?
}
?>
      <p class="style7">Back to <a href="#top">Top</a> or <a href="../index.php">Home</a></p>
    </div></td>
  </tr>
  
  <tr>
    <td bgcolor="#000000"><div align="center" class="style7"><font color="#FFFFFF">Copyright &copy; Bindinator Developers <? echo date("Y"); ?></font></div></td>
  </tr>
</table>
<? include('../footer.php'); ?>
</body>
</html>
